# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'ReactiveObjCTraining01' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactiveObjCTraining01
  pod 'ReactiveObjC', '~> 3.1.0'

  target 'ReactiveObjCTraining01Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactiveObjCTraining01UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
